name: vaex-dev
channels:
  - numba/label/dev
  - msys2
  - conda-forge
dependencies:
- aplus
- astropy
- blake3
- cython
- cachetools
- catboost
- diskcache
- fastapi
- filelock
- frozendict
- fsspec
- gcsfs
- geopandas
- graphviz
- h5py
- ipyvolume=0.6.0a6
- ipyvue
- ipyvuetify
- ipympl
- ipyleaflet
- lightgbm
- matplotlib-base
- notebook
- numba
- numpy<1.21
- pandas
- pcre
- pip
- plotly
- python-annoy
- pyarrow>=4.0.0
- pyqt
- pytest
- pytest-asyncio<0.14
- pytest-mpl
- pytest-timeout
- python-graphviz
- py-xgboost
- s3fs>=2021.8.0
- progressbar2
- scikit-learn
- scipy<1.7.2
- tabulate
- tornado
- xarray
- pip:
  - myst_parser
  - tensorflow==2.6.0
  - keras==2.6.0
